version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: meeting_db
    environment:
      POSTGRES_DB: meeting_db
      POSTGRES_USER: meeting_admin
      POSTGRES_PASSWORD: iVAP26hvSdyLBPNpZ0ZQVQQCwmNaybzUe031ZtAEL6u8cNLw96Q4rrHgydaOsslkeA0uiz1lsiKGYZyY1ZLw4aOJ7YcXU89eEt4SYzRLcsTfQcq6Z4s8P6wXLgV82x9u
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "127.0.0.1:5432:5432"  # Seulement accessible localement
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    command: [
      "postgres",
      "-c", "listen_addresses=*",  # Écoute sur toutes les interfaces pour le réseau Docker
      "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"
    ]
    networks:
      - meeting_network
    restart: unless-stopped

  # Backend NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meeting_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=meeting_admin
      - DB_PASSWORD=iVAP26hvSdyLBPNpZ0ZQVQQCwmNaybzUe031ZtAEL6u8cNLw96Q4rrHgydaOsslkeA0uiz1lsiKGYZyY1ZLw4aOJ7YcXU89eEt4SYzRLcsTfQcq6Z4s8P6wXLgV82x9u
      - DB_NAME=meeting_db
      - JWT_SECRET=XtV7JCR087OjF2R5N6l7G2ZbxLBJrxW5QsUU27ywrM4hEb0PIkMY2X0bJQnaM0aGW40UA2iqh3PR3R1coPPnu11gSTI0XlJCPfs8CS37DQRoKx1qBj4u0YjXqmsZ607T
      - APP_URL=http://192.168.1.72:3001
      - FRONTEND_URL=http://192.168.1.72:3000
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - meeting_network
    restart: unless-stopped

  # Frontend Next.js
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meeting_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://192.168.1.72:3001
    depends_on:
      - backend
    networks:
      - meeting_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  meeting_network:
    driver: bridge